# Generated by Django 3.2.12 on 2023-06-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fechaIngreso', models.DateTimeField()),
                ('fechaSalida', models.DateTimeField()),
                ('estadia', models.FloatField()),
                ('costo', models.FloatField()),
                ('cochera', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('dominio', models.CharField(max_length=50)),
            ],
        ),
    ]
