# Generated by Django 3.2.12 on 2023-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dominio', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('hora', models.TimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
