# Generated by Django 3.2.12 on 2023-06-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_auto_20230621_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocheras',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='estado',
        ),
    ]
