# Generated by Django 3.2.12 on 2023-06-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_auto_20230621_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cocheras',
        ),
    ]
