# Generated by Django 3.2.12 on 2023-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_delete_cocheras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='hora',
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
