# Generated by Django 3.2.12 on 2023-06-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0005_auto_20230623_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='fecha',
            new_name='fechaIngreso',
        ),
    ]
